--- # Specify Android OS Open source projects
sites:
 - name: e.foundation
   main_site: https://e.foundation/
   device_page: https://doc.e.foundation/devices/
   table: True

 - name: LineageOS
   main_site: https://lineageos.org/
   device_page: https://wiki.lineageos.org/devices/
   table: True

 - name: crDroid
   main_site: https://crdroid.net/
   device_page: https://crdroid.net/dl.php
   table: False

 - name: Resurrection Remix OS
   main_site: https://www.resurrectionremix.com/
   device_page: https://get.resurrectionremix.com/
   table: False


 - name: AospExtended ROM
   main_site: https://www.aospextended.com/
   device_page: https://www.aospextended.com/devices/
   table: False

recovery:
 - name: twrp
   main_site: https://twrp.me
   device_page: https://twrp.me/Devices/


standard_device:
   device_model: beryllium
   released_date: 2018
   device_vendor: Xiaomi
   device_name: Poco F1
   device_type: Phone
   device_codename: beryllium
   device_dimensions_height: [155.5 mm, 6.12 in]
   device_dimensions_width: [75.3 mm, 2.96 in]
   device_dimensions_depth: [8.8 mm, 0.35 in]
   device_display_type: IPS LCD
   device_display_resolution: 1080x2160
   device_soc: Qualcomm SDM845 Snapdragon 845
   device_cpu: Octa-core Kryo 385  4 x 2.8 GHz + 4 x 1.8 GHz
   device_gpu: Adreno 630
   device_ram: [6/8 GB LPDDR4X]
   device_internal_card_type: SD
   device_internal_card_size: 256 GB
   device_peripherals_sim: 2
   device_peripherals_bluetooth: 5 with A2DP + aptX HD
   device_peripherals_wifi: [802.11 a/b/g/n/ac, Dual-band, Wi-Fi Direct, Wi-Fi Display, DLNA, Hotspot]
   device_peripherals_usb: no
   device_peripherals_nfc: no
   device_peripherals_gps: yes
   device_peripherals_sensors: [Light, Proximity]
   device_number_of_cameras: 2
   device_parametres_of_cameras: [12 MP or 5 MP, Main Dual LED (dual tone) flash, 20 MP, Selfie flash]
   device_battery_removable: Non-removable
   device_battery_type: Li-Po
   device_battery_capacity: 4000 mAh
   device_os: oreo


